### PR TITLE
Python unit tests

### PR DESCRIPTION
**Pull request by iangudger**
Adds unit tests to Python SEADS API and Travis CI integration.

### CODE REVIEW

**Comment by ianlofs** [comment]
This looks good to merge although why did you add Google, Inc to the copyright?

**Comment by iangudger** [comment]
Google is my employer and owns all code that I write while I am employed by them. You and everythone else has a license to use it under the MIT license. I have discussed this with Ali and he is ok with this.

**Comment by ianlofs** [comment]
OK well that's cool, as long as Google can't sue us later on then its fine. Merging.

**Comment by iangudger** [comment]
Yeah, Google insists that we do this.

**Pull request merged**
